### ISSUE TITLE
Exceptions in Flow killing parent Oban process

### ISSUE THREAD

**Issue by cigrainger** [dashbitco/flow#110]
When there's an exception in Flow, the parent process dies. This is not good in cases like Oban where it leads to zombie jobs. I note that this happens in IEx as well (IEx restarts). Minimal example:

```elixir
defmodule WillDie do
  def dies(x) do
    raise "OH NO #{inspect(x)}"
  end
end

1..10 |> Flow.from_enumerable() |> Flow.map(&WillDie.dies/1) |> Enum.to_list()
```

I think there must be an obvious answer here to trap the exit and not crash the parent, but I don't know what it is.

**Comment by josevalim** [comment]
You could add `Process.flag(:trap_exit, true)` before you call Flow.

However, Oban should be able to handle broken links too and not leave zombie jobs. Even and without trapping exits. For example, even doing `spawn_link(fn -> raise "foo" end)` should be fine. Ping @sorentwo.

**Comment by cigrainger** [comment]
That's what I couldn't remember! `:trap_exit`! Thank you. That's fixed the problem for us. I'm also interested to see what @sorentwo think.

**Comment by sorentwo** [comment]
I'm surprised to hear that you're getting zombie jobs from crashing processes. This [property test](https://github.com/sorentwo/oban/blob/main/test/integration/executing_test.exs#L17) exercises jobs with a multitude of failures, including [linked processes crashing](https://github.com/sorentwo/oban/blob/main/test/support/worker.ex#L18).

In situations like this, where nested processes crash, the [producer traps exits](https://github.com/sorentwo/oban/blob/main/lib/oban/queue/producer.ex#L90) and handles transitioning the job.
