### ISSUE TITLE
Access previous windows

### ISSUE THREAD

**Issue by kozy** [dashbitco/flow#121]
Sometimes, when no events are received in a fixed window, i would like to access the previous windows values to create an event. What would be an elegant way to do this?

Would casting the item with Genserver.cast and then fetching the item later on cause any trouble? I have a feeling doing this outside of Flow logic might cause issues. 

Thank you!

**Comment by josevalim** [comment]
You would need to publish the events in the Flow to some place that holds the last event. Flow only holds temporary data. You could try using other windows too and roll your own version of fixed that preserves the last one.

**Comment by kozy** [comment]
Very helpful. I will try rolling my own window function then. It would be nice not to clutter the main flow with edge case logic too much.
