### ISSUE TITLE
Flow.from_specs and failed starts

### ISSUE THREAD

**Issue by isaacsanders** [dashbitco/flow#78]
Hey all!

I have been seeing an error that I think comes from `Flow.from_specs`. It assumes that the result of the `start_link` anonymous function is `{:ok, pid()}`, and when it is `{:error, term()}`, the output of the system is not easy to debug.

I can work on a PR for this, but I just wanted to put it here, if someone got to it first.

There is a discussion about how a failure should be handled, and I am personally of the opinion that it should fail on startup, but I understand that there might be different opinions on this.

**Comment by josevalim** [comment]
We should fail to boot as it likely fails today but improve the error message.

**Comment by isaacsanders** [comment]
Yeah, right now it is an exit, instead of a `{:error, reason}`.

**Comment by josevalim** [comment]
Ping.

**Comment by josevalim** [comment]
Hi @isaacsanders, do you still plan to submit a PR? Thanks.
